/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 03 10:41:20 GMT 2026
 */

package org.apache.syncope.core.spring.security;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Set;
import org.apache.cxf.rs.security.jose.jwt.JwtClaims;
import org.apache.syncope.common.lib.types.AuditElements;
import org.apache.syncope.common.lib.types.CipherAlgorithm;
import org.apache.syncope.core.persistence.api.entity.user.User;
import org.apache.syncope.core.spring.security.AuthDataAccessor;
import org.apache.syncope.core.spring.security.JWTAuthentication;
import org.apache.syncope.core.spring.security.SyncopeAuthenticationDetails;
import org.apache.syncope.core.spring.security.SyncopeGrantedAuthority;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.junit.runner.RunWith;
import org.springframework.security.core.Authentication;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AuthDataAccessor_ESTest extends AuthDataAccessor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      AuthDataAccessor authDataAccessor0 = new AuthDataAccessor();
      AuditElements.EventCategoryType auditElements_EventCategoryType0 = AuditElements.EventCategoryType.PUSH;
      AuditElements.Result auditElements_Result0 = AuditElements.Result.SUCCESS;
      Object object0 = new Object();
      Object[] objectArray0 = new Object[6];
      // Undeclared exception!
      try { 
        authDataAccessor0.audit(auditElements_EventCategoryType0, "Yj)5!3", (String) null, "", auditElements_Result0, object0, (Object) null, objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.spring.security.AuthDataAccessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      AuthDataAccessor authDataAccessor0 = new AuthDataAccessor();
      // Undeclared exception!
      try { 
        authDataAccessor0.findDomain("Invoking afterPropertiesSet() on bean with name '");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.spring.security.AuthDataAccessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      AuthDataAccessor authDataAccessor0 = new AuthDataAccessor();
      User user0 = mock(User.class, new ViolatedAssumptionAnswer());
      doReturn((CipherAlgorithm) null).when(user0).getCipherAlgorithm();
      doReturn((String) null).when(user0).getPassword();
      doReturn((String) null).when(user0).getUsername();
      // Undeclared exception!
      try { 
        authDataAccessor0.authenticate(user0, "XH;Jk$afA:<em**");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.spring.security.AuthDataAccessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      AuthDataAccessor authDataAccessor0 = new AuthDataAccessor();
      Set<SyncopeGrantedAuthority> set0 = authDataAccessor0.getAdminAuthorities();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      AuthDataAccessor authDataAccessor0 = new AuthDataAccessor();
      // Undeclared exception!
      try { 
        authDataAccessor0.getPassthroughResources((User) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.spring.security.AuthDataAccessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      AuthDataAccessor authDataAccessor0 = new AuthDataAccessor();
      // Undeclared exception!
      try { 
        authDataAccessor0.authenticate((Authentication) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.spring.security.AuthDataAccessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      AuthDataAccessor authDataAccessor0 = new AuthDataAccessor();
      // Undeclared exception!
      try { 
        authDataAccessor0.getJWTSSOProvider((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.spring.security.AuthDataAccessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      AuthDataAccessor authDataAccessor0 = new AuthDataAccessor();
      authDataAccessor0.adminUser = ".5) 1q[mCO";
      JwtClaims jwtClaims0 = new JwtClaims();
      jwtClaims0.setSubject(".5) 1q[mCO");
      JWTAuthentication jWTAuthentication0 = new JWTAuthentication(jwtClaims0, (SyncopeAuthenticationDetails) null);
      // Undeclared exception!
      try { 
        authDataAccessor0.authenticate(jWTAuthentication0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.spring.security.AuthDataAccessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      AuthDataAccessor authDataAccessor0 = new AuthDataAccessor();
      authDataAccessor0.adminUser = "5r9&~UJP4#z;";
      authDataAccessor0.anonymousUser = "5r9&~UJP4#z;";
      // Undeclared exception!
      try { 
        authDataAccessor0.getAuthorities("org.springframework.beans.BeanWrapperImpl$BeanPropertyHandler");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.spring.security.AuthDataAccessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      AuthDataAccessor authDataAccessor0 = new AuthDataAccessor();
      authDataAccessor0.anonymousUser = ".5) !qq[mCO";
      Set<SyncopeGrantedAuthority> set0 = authDataAccessor0.getAuthorities(".5) !qq[mCO");
      assertFalse(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      AuthDataAccessor authDataAccessor0 = new AuthDataAccessor();
      User user0 = mock(User.class, new ViolatedAssumptionAnswer());
      doReturn(true).when(user0).isMustChangePassword();
      Set<SyncopeGrantedAuthority> set0 = authDataAccessor0.getUserAuthorities(user0);
      assertFalse(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      AuthDataAccessor authDataAccessor0 = new AuthDataAccessor();
      User user0 = mock(User.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(user0).isMustChangePassword();
      // Undeclared exception!
      try { 
        authDataAccessor0.getUserAuthorities(user0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.spring.security.AuthDataAccessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      AuthDataAccessor authDataAccessor0 = new AuthDataAccessor();
      authDataAccessor0.adminUser = ".5) !qq[mCO";
      JwtClaims jwtClaims0 = new JwtClaims();
      JWTAuthentication jWTAuthentication0 = new JWTAuthentication(jwtClaims0, (SyncopeAuthenticationDetails) null);
      // Undeclared exception!
      try { 
        authDataAccessor0.authenticate(jWTAuthentication0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.spring.security.AuthDataAccessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      AuthDataAccessor authDataAccessor0 = new AuthDataAccessor();
      AuditElements.EventCategoryType auditElements_EventCategoryType0 = AuditElements.EventCategoryType.CUSTOM;
      AuditElements.Result auditElements_Result0 = AuditElements.Result.SUCCESS;
      // Undeclared exception!
      try { 
        authDataAccessor0.audit(auditElements_EventCategoryType0, ".IT", ".IT", ".IT", auditElements_Result0, auditElements_Result0, auditElements_Result0, (Object[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.spring.security.AuthDataAccessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      AuthDataAccessor authDataAccessor0 = new AuthDataAccessor();
      // Undeclared exception!
      try { 
        authDataAccessor0.removeExpired("digester.saltSizeBytes not found, reverting to default");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.spring.security.AuthDataAccessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      AuthDataAccessor authDataAccessor0 = new AuthDataAccessor();
      authDataAccessor0.adminUser = "5r9&~UJP4#z;";
      authDataAccessor0.anonymousUser = "tFf{&Iu$$:";
      Set<SyncopeGrantedAuthority> set0 = authDataAccessor0.getAuthorities("5r9&~UJP4#z;");
      assertTrue(set0.isEmpty());
  }
}
