/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Jun 03 10:41:20 GMT 2026
 */

package org.apache.syncope.core.spring.security;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class AuthDataAccessor_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.syncope.core.spring.security.AuthDataAccessor"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/home/leonardo/uni/isw2/SyncopeNoTest"); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("user.language", "it"); 
    java.lang.System.setProperty("user.country", "IT"); 
    java.lang.System.setProperty("user.home", "/home/leonardo"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(AuthDataAccessor_ESTest_scaffolding.class.getClassLoader() ,
      "com.fasterxml.jackson.annotation.JsonProperty",
      "org.springframework.security.core.userdetails.UsernameNotFoundException",
      "org.apache.syncope.core.persistence.api.entity.ProvidedKeyEntity",
      "org.apache.syncope.core.persistence.api.SyncopeLoader",
      "org.apache.syncope.core.spring.security.JWTSSOProvider",
      "org.apache.syncope.core.persistence.api.entity.Realm",
      "org.apache.syncope.core.persistence.api.entity.PlainAttr",
      "org.apache.syncope.core.persistence.api.entity.AnyType",
      "org.apache.syncope.core.persistence.api.entity.Domain",
      "org.apache.syncope.core.persistence.api.entity.Entity",
      "org.apache.syncope.common.lib.types.AuditElements",
      "org.apache.commons.lang3.StringUtils",
      "com.fasterxml.jackson.annotation.JacksonAnnotation",
      "org.apache.syncope.core.persistence.api.entity.AnnotatedEntity",
      "org.apache.syncope.core.persistence.api.dao.GroupDAO",
      "org.apache.commons.lang3.builder.ToStringStyle$NoClassNameToStringStyle",
      "org.apache.commons.lang3.tuple.Pair",
      "org.apache.commons.lang3.builder.IDKey",
      "org.apache.cxf.rs.security.jose.jwt.JwtClaims",
      "org.apache.commons.lang3.builder.ToStringStyle$JsonToStringStyle",
      "org.apache.commons.lang3.builder.HashCodeBuilder",
      "org.springframework.security.core.AuthenticationException",
      "org.apache.syncope.core.persistence.api.entity.Role",
      "org.apache.syncope.core.persistence.api.entity.AnyTypeClass",
      "org.apache.syncope.core.spring.security.SyncopeAuthenticationDetails",
      "org.apache.syncope.core.persistence.api.dao.UserDAO",
      "org.apache.syncope.core.provisioning.api.EntitlementsHolder",
      "org.apache.syncope.core.persistence.api.dao.DAO",
      "org.apache.syncope.core.persistence.api.dao.AnyTypeDAO",
      "org.apache.syncope.core.persistence.api.dao.DomainDAO",
      "org.springframework.security.authentication.AccountStatusException",
      "org.springframework.security.core.GrantedAuthority",
      "org.apache.syncope.core.provisioning.api.AuditManager",
      "org.apache.syncope.core.provisioning.api.ConnectorFactory",
      "org.apache.commons.lang3.builder.ToStringBuilder",
      "org.apache.syncope.core.persistence.api.entity.group.Group",
      "org.springframework.security.core.Authentication",
      "org.apache.syncope.core.persistence.api.dao.ConfDAO",
      "org.apache.commons.lang3.builder.ToStringStyle$MultiLineToStringStyle",
      "org.apache.syncope.core.persistence.api.entity.user.UPlainAttr",
      "org.apache.syncope.core.persistence.api.dao.AnySearchDAO",
      "org.apache.syncope.common.lib.types.AuditElements$Result",
      "org.apache.syncope.core.persistence.api.entity.GroupableRelatable",
      "org.apache.commons.lang3.builder.ToStringStyle",
      "org.apache.commons.lang3.ArrayUtils",
      "org.apache.commons.lang3.builder.HashCodeExclude",
      "org.apache.commons.lang3.builder.ToStringExclude",
      "org.apache.syncope.core.persistence.api.entity.user.URelationship",
      "org.apache.syncope.core.spring.security.SyncopeGrantedAuthority",
      "org.apache.syncope.core.provisioning.api.MappingManager",
      "org.springframework.security.authentication.DisabledException",
      "org.apache.syncope.core.persistence.api.dao.RealmDAO",
      "org.apache.syncope.core.spring.security.JWTAuthentication",
      "org.springframework.security.authentication.AuthenticationCredentialsNotFoundException",
      "org.apache.commons.lang3.builder.ToStringStyle$ShortPrefixToStringStyle",
      "com.fasterxml.jackson.annotation.JsonProperty$Access",
      "org.apache.syncope.core.persistence.api.entity.user.UMembership",
      "org.apache.syncope.common.lib.types.CipherAlgorithm",
      "org.apache.syncope.core.spring.security.Encryptor",
      "org.apache.syncope.common.lib.types.AuditElements$EventCategoryType",
      "org.apache.commons.lang3.builder.ReflectionToStringBuilder",
      "org.apache.syncope.core.persistence.api.entity.anyobject.AnyObject",
      "org.springframework.security.authentication.AuthenticationServiceException",
      "org.apache.syncope.core.persistence.api.entity.user.User",
      "org.apache.syncope.core.spring.security.AuthDataAccessor",
      "org.apache.syncope.core.persistence.api.dao.AccessTokenDAO",
      "org.apache.syncope.core.persistence.api.ImplementationLookup",
      "org.apache.syncope.core.persistence.api.entity.Membership",
      "org.apache.commons.lang3.tuple.ImmutablePair",
      "org.apache.cxf.rs.security.jose.jws.JwsSignatureVerifier",
      "org.apache.cxf.jaxrs.json.basic.JsonMapObject",
      "org.apache.syncope.common.lib.PropertyUtils",
      "org.apache.commons.lang3.builder.ToStringStyle$SimpleToStringStyle",
      "org.apache.syncope.core.persistence.api.entity.resource.ExternalResource",
      "org.apache.commons.lang3.Validate",
      "org.apache.syncope.core.persistence.api.dao.AnyDAO",
      "org.apache.syncope.core.persistence.api.entity.Relationship",
      "org.apache.commons.lang3.builder.ToStringStyle$DefaultToStringStyle",
      "org.apache.commons.lang3.builder.Builder",
      "org.apache.commons.lang3.builder.ToStringStyle$NoFieldNameToStringStyle",
      "org.apache.syncope.core.persistence.api.entity.RelationshipType",
      "org.apache.syncope.core.persistence.api.entity.Any",
      "org.apache.syncope.core.persistence.api.entity.DynRealm",
      "org.apache.syncope.core.persistence.api.entity.GroupablePlainAttr",
      "org.apache.syncope.core.persistence.api.entity.user.SecurityQuestion"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("org.apache.syncope.core.persistence.api.entity.user.User", false, AuthDataAccessor_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(AuthDataAccessor_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.syncope.common.lib.PropertyUtils",
      "org.apache.commons.lang3.tuple.Pair",
      "org.apache.commons.lang3.tuple.ImmutablePair",
      "org.apache.syncope.core.spring.security.Encryptor",
      "org.apache.commons.lang3.StringUtils",
      "org.apache.commons.lang3.ArrayUtils",
      "org.apache.syncope.common.lib.types.CipherAlgorithm",
      "org.apache.syncope.core.spring.security.SyncopeGrantedAuthority",
      "org.apache.syncope.core.spring.security.AuthDataAccessor",
      "org.springframework.transaction.annotation.Isolation",
      "org.springframework.transaction.annotation.Propagation",
      "org.apache.syncope.core.persistence.api.dao.search.AttributeCond$Type",
      "org.apache.syncope.core.persistence.api.dao.search.SearchCond$Type",
      "org.apache.syncope.common.lib.types.AnyTypeKind",
      "org.apache.syncope.core.provisioning.api.EntitlementsHolder",
      "org.apache.syncope.core.spring.ApplicationContextProvider",
      "com.fasterxml.jackson.annotation.JsonCreator$Mode",
      "com.fasterxml.jackson.annotation.JsonProperty$Access",
      "org.apache.cxf.jaxrs.json.basic.JsonMapObject",
      "org.apache.cxf.rs.security.jose.jwt.JwtClaims",
      "org.apache.syncope.core.spring.security.JWTAuthentication",
      "org.springframework.core.SimpleAliasRegistry",
      "org.springframework.beans.factory.support.DefaultSingletonBeanRegistry",
      "org.springframework.beans.factory.support.FactoryBeanRegistrySupport",
      "org.springframework.beans.factory.support.AbstractBeanFactory",
      "org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory",
      "org.springframework.util.ClassUtils",
      "org.springframework.util.Assert",
      "org.springframework.beans.factory.support.DefaultListableBeanFactory",
      "org.springframework.security.authentication.AbstractAuthenticationToken",
      "org.springframework.security.authentication.TestingAuthenticationToken",
      "org.apache.cxf.rs.security.jose.common.JoseHeaders",
      "org.apache.cxf.rs.security.jose.jws.JwsHeaders",
      "org.springframework.core.io.DefaultResourceLoader",
      "org.springframework.context.support.AbstractApplicationContext",
      "org.springframework.context.support.AbstractRefreshableApplicationContext",
      "org.springframework.context.support.AbstractRefreshableConfigApplicationContext",
      "org.springframework.context.support.AbstractXmlApplicationContext",
      "org.springframework.context.support.FileSystemXmlApplicationContext",
      "org.springframework.core.io.AbstractResource",
      "org.springframework.core.io.DescriptiveResource",
      "org.springframework.security.core.authority.AuthorityUtils",
      "org.springframework.context.support.GenericApplicationContext",
      "org.springframework.context.support.GenericXmlApplicationContext",
      "org.springframework.security.core.authority.SimpleGrantedAuthority",
      "org.springframework.util.StringUtils",
      "org.apache.cxf.common.util.StringUtils",
      "org.jasypt.digest.StandardStringDigester",
      "org.jasypt.digest.StandardByteDigester",
      "org.jasypt.contrib.org.apache.commons.codec_1_3.binary.Base64",
      "org.jasypt.commons.CommonUtils",
      "org.apache.commons.lang3.builder.HashCodeBuilder",
      "org.apache.commons.lang3.Validate",
      "org.apache.commons.lang3.builder.IDKey",
      "org.apache.commons.lang3.builder.ToStringStyle$DefaultToStringStyle",
      "org.apache.commons.lang3.builder.ToStringStyle$MultiLineToStringStyle",
      "org.apache.commons.lang3.builder.ToStringStyle$NoFieldNameToStringStyle",
      "org.apache.commons.lang3.builder.ToStringStyle$ShortPrefixToStringStyle",
      "org.apache.commons.lang3.builder.ToStringStyle$SimpleToStringStyle",
      "org.apache.commons.lang3.builder.ToStringStyle$NoClassNameToStringStyle",
      "org.apache.commons.lang3.builder.ToStringStyle$JsonToStringStyle",
      "org.apache.commons.lang3.builder.ToStringStyle",
      "org.apache.commons.lang3.builder.ToStringBuilder",
      "org.apache.commons.lang3.builder.ReflectionToStringBuilder",
      "org.jasypt.salt.RandomSaltGenerator",
      "org.jasypt.normalization.Normalizer",
      "org.jasypt.exceptions.EncryptionOperationNotPossibleException",
      "org.springframework.security.authentication.UsernamePasswordAuthenticationToken",
      "org.springframework.security.authentication.AnonymousAuthenticationToken",
      "org.springframework.util.CollectionUtils",
      "org.springframework.security.authentication.RememberMeAuthenticationToken",
      "org.apache.syncope.core.spring.security.SyncopeJWTSSOProvider",
      "org.springframework.context.annotation.AnnotationConfigApplicationContext",
      "org.apache.cxf.common.logging.JDKBugHacks",
      "org.apache.cxf.common.logging.JDKBugHacks$1",
      "org.apache.cxf.common.classloader.ClassLoaderUtils",
      "org.apache.cxf.common.classloader.ClassLoaderUtils$1",
      "org.apache.cxf.common.classloader.ClassLoaderUtils$ClassLoaderHolder",
      "org.apache.cxf.common.logging.JDKBugHacks$2",
      "org.apache.cxf.common.classloader.ClassLoaderUtils$ClassLoaderHolder$1",
      "org.apache.cxf.common.logging.LogUtils$1",
      "org.apache.cxf.common.logging.AbstractDelegatingLogger",
      "org.apache.cxf.common.logging.Slf4jLogger",
      "org.apache.cxf.common.logging.LogUtils$3",
      "org.apache.cxf.common.logging.LogUtils$4",
      "org.apache.cxf.common.logging.LogUtils$2",
      "org.apache.cxf.common.i18n.BundleUtils",
      "org.apache.cxf.common.util.PackageUtils",
      "org.apache.cxf.common.i18n.BundleUtils$2",
      "org.apache.cxf.common.i18n.BundleUtils$1",
      "org.apache.cxf.common.logging.LogUtils",
      "org.apache.cxf.rs.security.jose.jws.JwsUtils",
      "org.apache.cxf.phase.PhaseInterceptorChain",
      "org.apache.cxf.rs.security.jose.common.KeyManagementUtils",
      "org.springframework.core.AttributeAccessorSupport",
      "org.springframework.beans.BeanMetadataAttributeAccessor",
      "org.springframework.beans.factory.support.AbstractBeanDefinition",
      "org.springframework.beans.factory.support.RootBeanDefinition",
      "org.springframework.beans.factory.support.BeanDefinitionResource",
      "org.springframework.core.io.AbstractFileResolvingResource",
      "org.springframework.core.io.ClassPathResource",
      "org.springframework.context.support.ClassPathXmlApplicationContext",
      "com.fasterxml.jackson.databind.DeserializationFeature",
      "org.apache.commons.io.FilenameUtils",
      "org.apache.commons.io.IOCase",
      "org.springframework.context.support.StaticApplicationContext",
      "org.springframework.security.crypto.bcrypt.BCrypt",
      "org.apache.commons.lang3.builder.EqualsBuilder",
      "org.apache.syncope.core.provisioning.api.utils.RealmUtils",
      "groovyjarjarasm.asm.MethodVisitor",
      "groovyjarjarasm.asm.tree.MethodNode",
      "groovyjarjarasm.asm.tree.InsnList",
      "groovyjarjarasm.asm.commons.AnalyzerAdapter",
      "groovyjarjarasm.asm.Type",
      "org.apache.cxf.rs.security.jose.jwk.JsonWebKey",
      "org.springframework.context.support.GenericGroovyApplicationContext",
      "org.springframework.beans.PropertyEditorRegistrySupport",
      "org.springframework.beans.TypeConverterSupport",
      "org.springframework.beans.AbstractPropertyAccessor",
      "org.springframework.beans.AbstractNestablePropertyAccessor",
      "groovyjarjarasm.asm.tree.AbstractInsnNode",
      "groovyjarjarasm.asm.tree.FrameNode",
      "org.springframework.core.io.InputStreamResource",
      "com.fasterxml.jackson.databind.JsonSerializable$Base",
      "com.fasterxml.jackson.databind.JsonNode",
      "com.fasterxml.jackson.databind.node.BaseJsonNode",
      "com.fasterxml.jackson.databind.node.ContainerNode",
      "com.fasterxml.jackson.databind.node.ArrayNode",
      "org.apache.cxf.helpers.CastUtils",
      "org.springframework.core.io.UrlResource",
      "org.springframework.core.io.FileUrlResource",
      "org.springframework.core.io.ByteArrayResource",
      "org.springframework.core.io.ClassRelativeResourceLoader",
      "org.springframework.core.io.ClassRelativeResourceLoader$ClassRelativeContextResource",
      "org.springframework.transaction.support.SimpleTransactionScope",
      "org.springframework.beans.factory.config.BeanExpressionContext",
      "org.springframework.beans.factory.support.StaticListableBeanFactory",
      "groovyjarjarasm.asm.util.Printer",
      "groovyjarjarasm.asm.util.Textifier",
      "org.springframework.core.io.PathResource",
      "com.fasterxml.jackson.databind.node.ValueNode",
      "com.fasterxml.jackson.databind.node.NumericNode",
      "com.fasterxml.jackson.databind.node.FloatNode",
      "org.springframework.context.ApplicationEvent",
      "org.springframework.context.PayloadApplicationEvent",
      "org.springframework.core.ResolvableType$EmptyType",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceType",
      "org.springframework.util.ConcurrentReferenceHashMap",
      "org.springframework.util.ConcurrentReferenceHashMap$Segment",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceManager",
      "org.springframework.core.ResolvableType",
      "org.springframework.core.SerializableTypeWrapper",
      "org.springframework.core.ResolvableType$SyntheticParameterizedType",
      "org.springframework.core.ResolvableType$TypeVariablesVariableResolver",
      "org.springframework.util.ObjectUtils",
      "org.springframework.util.ConcurrentReferenceHashMap$Restructure",
      "org.springframework.util.ConcurrentReferenceHashMap$Task",
      "org.springframework.util.ConcurrentReferenceHashMap$1",
      "org.springframework.util.ConcurrentReferenceHashMap$TaskOption",
      "org.springframework.util.ConcurrentReferenceHashMap$Entries",
      "org.springframework.util.ConcurrentReferenceHashMap$Segment$1",
      "org.springframework.util.ConcurrentReferenceHashMap$Entry",
      "org.springframework.util.ConcurrentReferenceHashMap$SoftEntryReference",
      "org.springframework.beans.factory.config.AbstractFactoryBean",
      "org.springframework.beans.factory.config.SetFactoryBean",
      "com.fasterxml.jackson.databind.DatabindContext",
      "com.fasterxml.jackson.databind.JsonSerializer",
      "com.fasterxml.jackson.databind.ser.std.StdSerializer",
      "com.fasterxml.jackson.databind.ser.impl.FailingSerializer",
      "com.fasterxml.jackson.databind.ser.impl.UnknownSerializer",
      "com.fasterxml.jackson.databind.SerializerProvider",
      "com.fasterxml.jackson.databind.ser.DefaultSerializerProvider",
      "com.fasterxml.jackson.databind.ser.DefaultSerializerProvider$Impl",
      "com.fasterxml.jackson.databind.ser.std.NullSerializer",
      "com.fasterxml.jackson.databind.ser.SerializerCache",
      "com.fasterxml.jackson.core.TreeCodec",
      "com.fasterxml.jackson.core.ObjectCodec",
      "com.fasterxml.jackson.core.type.ResolvedType",
      "com.fasterxml.jackson.databind.JavaType",
      "com.fasterxml.jackson.databind.type.TypeBindings",
      "com.fasterxml.jackson.databind.type.TypeBase",
      "com.fasterxml.jackson.databind.type.SimpleType",
      "com.fasterxml.jackson.databind.AnnotationIntrospector",
      "com.fasterxml.jackson.databind.ext.Java7SupportImpl",
      "com.fasterxml.jackson.databind.util.ClassUtil",
      "com.fasterxml.jackson.databind.ext.Java7Support",
      "com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector",
      "com.fasterxml.jackson.databind.util.LRUMap",
      "com.fasterxml.jackson.databind.cfg.BaseSettings",
      "com.fasterxml.jackson.databind.type.TypeParser",
      "com.fasterxml.jackson.databind.type.TypeFactory",
      "com.fasterxml.jackson.databind.util.StdDateFormat",
      "com.fasterxml.jackson.core.Base64Variant",
      "com.fasterxml.jackson.core.Base64Variants",
      "com.fasterxml.jackson.databind.ObjectMapper",
      "com.fasterxml.jackson.core.JsonFactory$Feature",
      "com.fasterxml.jackson.core.JsonGenerator$Feature",
      "com.fasterxml.jackson.core.io.SerializedString",
      "com.fasterxml.jackson.core.util.DefaultPrettyPrinter",
      "com.fasterxml.jackson.core.JsonFactory",
      "com.fasterxml.jackson.databind.MappingJsonFactory",
      "com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
      "com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer$TableInfo",
      "com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer",
      "com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer$TableInfo",
      "com.fasterxml.jackson.databind.jsontype.SubtypeResolver",
      "com.fasterxml.jackson.databind.jsontype.impl.StdSubtypeResolver",
      "com.fasterxml.jackson.databind.util.RootNameLookup",
      "com.fasterxml.jackson.databind.introspect.SimpleMixInResolver",
      "com.fasterxml.jackson.databind.introspect.ClassIntrospector",
      "com.fasterxml.jackson.databind.introspect.AnnotationCollector$NoAnnotations",
      "com.fasterxml.jackson.databind.introspect.AnnotationCollector",
      "com.fasterxml.jackson.databind.introspect.AnnotatedClassResolver",
      "com.fasterxml.jackson.databind.introspect.Annotated",
      "com.fasterxml.jackson.databind.introspect.AnnotatedClass$Creators",
      "com.fasterxml.jackson.databind.introspect.AnnotatedClass",
      "com.fasterxml.jackson.databind.BeanDescription",
      "com.fasterxml.jackson.databind.introspect.BasicBeanDescription",
      "com.fasterxml.jackson.databind.introspect.BasicClassIntrospector",
      "com.fasterxml.jackson.databind.cfg.ConfigOverrides",
      "com.fasterxml.jackson.annotation.JsonInclude$Include",
      "com.fasterxml.jackson.annotation.JsonInclude$Value",
      "com.fasterxml.jackson.annotation.Nulls",
      "com.fasterxml.jackson.annotation.JsonSetter$Value",
      "com.fasterxml.jackson.databind.introspect.VisibilityChecker$Std",
      "com.fasterxml.jackson.annotation.JsonFormat$Features",
      "com.fasterxml.jackson.annotation.JsonFormat$Value",
      "com.fasterxml.jackson.databind.cfg.MapperConfig",
      "com.fasterxml.jackson.databind.cfg.ConfigOverride",
      "com.fasterxml.jackson.databind.cfg.ConfigOverride$Empty",
      "com.fasterxml.jackson.databind.MapperFeature",
      "com.fasterxml.jackson.databind.cfg.MapperConfigBase",
      "com.fasterxml.jackson.core.util.DefaultPrettyPrinter$NopIndenter",
      "com.fasterxml.jackson.core.util.DefaultPrettyPrinter$FixedSpaceIndenter",
      "com.fasterxml.jackson.core.util.DefaultIndenter",
      "com.fasterxml.jackson.core.util.Separators",
      "com.fasterxml.jackson.core.PrettyPrinter",
      "com.fasterxml.jackson.databind.SerializationConfig",
      "com.fasterxml.jackson.databind.cfg.ContextAttributes",
      "com.fasterxml.jackson.databind.cfg.ContextAttributes$Impl",
      "com.fasterxml.jackson.databind.SerializationFeature",
      "com.fasterxml.jackson.databind.DeserializationConfig",
      "com.fasterxml.jackson.databind.node.JsonNodeFactory",
      "com.fasterxml.jackson.databind.DeserializationContext",
      "com.fasterxml.jackson.databind.deser.DefaultDeserializationContext",
      "com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl",
      "com.fasterxml.jackson.databind.deser.DeserializerFactory",
      "com.fasterxml.jackson.databind.PropertyName",
      "com.fasterxml.jackson.databind.deser.BasicDeserializerFactory",
      "com.fasterxml.jackson.databind.deser.std.StdKeyDeserializers",
      "com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
      "com.fasterxml.jackson.databind.deser.BeanDeserializerFactory",
      "com.fasterxml.jackson.databind.deser.DeserializerCache",
      "com.fasterxml.jackson.databind.ser.SerializerFactory",
      "com.fasterxml.jackson.databind.ser.std.StdScalarSerializer",
      "com.fasterxml.jackson.databind.ser.std.StringSerializer",
      "com.fasterxml.jackson.databind.ser.std.ToStringSerializer",
      "com.fasterxml.jackson.databind.ser.std.NumberSerializers",
      "com.fasterxml.jackson.databind.ser.std.NumberSerializers$Base",
      "com.fasterxml.jackson.databind.ser.std.NumberSerializers$IntegerSerializer",
      "com.fasterxml.jackson.core.JsonParser$NumberType",
      "com.fasterxml.jackson.databind.ser.std.NumberSerializers$LongSerializer",
      "com.fasterxml.jackson.databind.ser.std.NumberSerializers$IntLikeSerializer",
      "com.fasterxml.jackson.databind.ser.std.NumberSerializers$ShortSerializer",
      "com.fasterxml.jackson.databind.ser.std.NumberSerializers$DoubleSerializer",
      "com.fasterxml.jackson.databind.ser.std.NumberSerializers$FloatSerializer",
      "com.fasterxml.jackson.databind.ser.std.BooleanSerializer",
      "com.fasterxml.jackson.databind.ser.std.NumberSerializer",
      "com.fasterxml.jackson.databind.ser.std.DateTimeSerializerBase",
      "com.fasterxml.jackson.databind.ser.std.CalendarSerializer",
      "com.fasterxml.jackson.databind.ser.std.DateSerializer",
      "com.fasterxml.jackson.databind.ser.std.StdJdkSerializers",
      "com.fasterxml.jackson.databind.ser.std.UUIDSerializer",
      "com.fasterxml.jackson.databind.ser.BasicSerializerFactory",
      "com.fasterxml.jackson.databind.cfg.SerializerFactoryConfig",
      "com.fasterxml.jackson.databind.ser.BeanSerializerFactory",
      "com.fasterxml.jackson.databind.introspect.VisibilityChecker$1",
      "org.springframework.security.core.AuthenticationException",
      "org.springframework.security.authentication.AuthenticationCredentialsNotFoundException"
    );
  }
}
