name: "ISW2 Selected Tests + SonarCloud"

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  selected-tests-and-sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 25
          cache: 'maven'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Show versions
        run: |
          java -version
          mvn -version

      - name: Test ContentLoaderHandler
        run: >
          mvn -B -e -pl core/persistence-neo4j -am
          -DskipTests=false
          -Dmaven.build.cache.skipCache=true
          -Dmodernizer.skip=true
          -Dianal.phase=none
          -Drat.skip=true
          -Dcheckstyle.skip=true
          test

      - name: Test DefaultJobManager
        run: >
          mvn -B -e -pl core/provisioning-java -am
          -DskipTests=false
          -Dmaven.build.cache.skipCache=true
          -Dmodernizer.skip=true
          -Dianal.phase=none
          -Drat.skip=true
          -Dcheckstyle.skip=true
          test

      - name: Analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn -B -e
          -DskipTests=true
          -Dmaven.build.cache.skipCache=true
          -Dmodernizer.skip=true
          -Dianal.phase=none
          -Drat.skip=true
          -Dcheckstyle.skip=true
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=polidori1999_provasmell
          -Dsonar.organization=polidori1999
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}